// AUTO-GENERATED by gen-flavour-engine-browser.mjs from
// Automation/core/src/flavour-engine.mjs. Do not hand-edit — re-run the
// generator instead so this never drifts from the canonical source.
// Exposes window.FlavourEngine = { FLAVOUR_ENGINE, selectFlavour, buildFlavourPromptBlock }.
(function(global){
// Shared Editorial Flavour Engine — the single source of truth for flavour
// definitions and selection logic across notes-factory, long-post-factory,
// update-factory, and (eventually) the Automation pipeline.
//
// Canonical source: this file (ESM, for Node). A browser-consumable mirror
// is generated by gen-flavour-engine-browser.mjs into shared/flavour-engine.js
// — never hand-edit that file, re-run the generator instead.
//
// Design principle this file exists to enforce: the Master Prompt states
// EDITORIAL POLICY only ("pick a flavour from the supplied options, adapt to
// the topic, never force it") — it never lists or reasons about individual
// flavours. Everything about WHICH flavours exist and HOW one gets picked
// lives here instead, so adding flavour #12 or changing the selection
// heuristic never touches the Master Prompt. See
// Automation/content-memory/README.md for how a selection gets recorded.
//
// A flavour changes real teaching strategy (opening logic, teaching
// sequence, example strategy, misconception treatment, practice-question
// strategy) — never cosmetic wording, card labels, or tone. `flow` is a
// compact `>`-separated string naming the actual editorial sequence a
// flavour implies, not a rendering instruction.

const FLAVOUR_ENGINE = [
  { id: 'concept-first', goal: 'build the core idea cleanly before anything else', flow: 'concept > example > application > practice', best_for: ['abstract or definitional topics', 'first exposure to a new term'], signals: ['definition', 'concept', 'kya hai', 'परिभाषा', 'अर्थ'] },
  { id: 'misconception-first', goal: 'correct the most likely misunderstanding before teaching the rule', flow: 'misconception > correction > rule > application', best_for: ['CDP', 'Language', 'Science'], signals: ['confusion', 'galti', 'गलती', 'mistake', 'गलतफहमी'] },
  { id: 'problem-first', goal: 'open with a hard real question, unpack what is needed to solve it', flow: 'problem > concept > solution > generalize > practice', best_for: ['exam-heavy topics with a signature PYQ', 'applied/quantitative topics'], signals: ['pyq', 'question', 'solve', 'numerical', 'केस-स्टडी'] },
  { id: 'worked-example', goal: 'learn through solving', flow: 'problem > worked-solution > reasoning > variation', best_for: ['Maths', 'Science'], signals: ['calculate', 'formula', 'सूत्र', 'solve', 'steps', 'method'] },
  { id: 'compare-and-contrast', goal: 'separate easily confused concepts', flow: 'shared-ground > difference > boundary-cases > practice', best_for: ['Language', 'History', 'Science', 'CDP'], signals: ['vs', 'और', 'अंतर', 'difference', 'compare', 'तुलना'] },
  { id: 'question-led', goal: 'let a sequence of practice questions drive the explanation', flow: 'question > explanation > question > explanation > summary', best_for: ['revision-adjacent topics with a large question bank'], signals: ['practice', 'questions', 'अभ्यास', 'quiz'] },
  { id: 'exam-trap-first', goal: 'open with the specific way this exam tricks candidates on this topic', flow: 'trap > why-it-works > correct-approach > practice', best_for: ['topics with a documented distractor pattern'], signals: ['trap', 'trick', 'distractor', 'जाल'] },
  { id: 'classroom-situation', goal: 'ground the whole topic in a realistic classroom scenario', flow: 'scenario > teacher-decision > theory-link > practice', best_for: ['CDP/Pedagogy topics', 'teacher-eligibility exams'], signals: ['classroom', 'teacher', 'student', 'कक्षा', 'शिक्षक', 'pedagogy'] },
  { id: 'classification', goal: 'teach by building out a clean classification/taxonomy', flow: 'category-map > sub-type-detail > examples > practice', best_for: ['Science/EVS/Geography topics with real sub-types'], signals: ['types', 'kinds', 'प्रकार', 'classification', 'category'] },
  { id: 'chronology-cause-effect', goal: 'teach as a sequence of events with causes and effects', flow: 'timeline > cause > effect > exam-relevance', best_for: ['History topics', 'policy-evolution topics'], signals: ['history', 'timeline', 'कब', 'इतिहास', 'causes', 'policy'] },
  { id: 'revision-focused', goal: 'compress and rapid-fire everything already known, exam-eve style', flow: 'rapid-recap > trap-list > mnemonics > quick-quiz', best_for: ['topics near the end of a subject, or an explicit revision ask'], signals: ['revision', 'recap', 'जल्दी', 'last-minute', 'summary'] },
  { id: 'rule-exception', goal: 'teach the general rule, then the exceptions that actually get tested', flow: 'rule > typical-case > exception > why-the-exception-exists > practice', best_for: ['Language', 'Maths', 'Science'], signals: ['exception', 'अपवाद', 'irregular', 'special case', 'rule'] },
  { id: 'case-to-concept', goal: 'start from a real/specific case and generalize the concept out of it', flow: 'specific-case > pattern-noticed > general-concept > practice', best_for: ['History', 'Geography', 'CDP', 'Science'], signals: ['case study', 'उदाहरण से', 'incident', 'example-led'] },
  { id: 'evidence-to-conclusion', goal: 'walk through the evidence before stating the conclusion, not after', flow: 'evidence > pattern > conclusion > exam-relevance', best_for: ['History', 'Geography', 'Science'], signals: ['evidence', 'प्रमाण', 'data', 'observation', 'सबूत'] },
  { id: 'process-first', goal: 'teach a multi-step process in the order it actually happens', flow: 'trigger > step-by-step-process > outcome > exam-application', best_for: ['Science/EVS', 'Geography', 'CDP'], signals: ['process', 'प्रक्रिया', 'stages', 'mechanism', 'cycle'] },
];

// -------- selection --------
// Priority order (never a blind cycle, never pure randomness):
//   1. topic suitability      — keyword `signals` match, scored highest
//   2. subject suitability    — light per-subject affinity bonus
//   3. exam suitability       — folded into subject affinity today (no
//                                exam-only signal has a real basis yet;
//                                EXAM_PROFILES-level nuance already lives in
//                                the Master Prompt's TEACHING LEVEL/exam text)
//   4. teaching value         — encoded in `signals`/affinities themselves,
//                                which model actual topic/subject fit, not
//                                arbitrary preference
//   5. recent content-memory  — repetition penalty, below
//   6. avoid unnecessary reps — the penalty only demotes, never excludes, so
//                                a genuinely best-fit flavour used recently
//                                can still win (see TIE_EPSILON note)
//   7. randomness             — ONLY as a last-resort tie-break (hash of
//                                topic/exam/subject, not Math.random()) when
//                                nothing above distinguishes two flavours

const RECENT_WINDOW = 5;   // how many recent same-exam/subject records count against repetition
const TIE_EPSILON = 0.5;   // scores within this range of the top score are treated as tied —
                            // must stay below the smallest real signal increment (1, a subject-
                            // affinity bonus) so an actual better-fitting flavour always wins;
                            // it only catches genuine exact ties (e.g. the concept-first anchor).

function hashString(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function scoreFlavour(flavour, topicLower, subjectLower, recentIds) {
  let score = 0;
  for (const kw of flavour.signals) if (topicLower.includes(kw)) score += 3;
  // light subject-level defaults, additive on top of keyword matching above —
  // these are hints, not hard rules, so a strong topic-keyword match on a
  // different flavour can still outscore them.
  if (subjectLower.includes('math') && (flavour.id === 'worked-example' || flavour.id === 'problem-first')) score += 2;
  if ((subjectLower.includes('cdp') || subjectLower.includes('pedagog')) && (flavour.id === 'classroom-situation' || flavour.id === 'misconception-first' || flavour.id === 'case-to-concept')) score += 2;
  if (subjectLower.includes('history') && (flavour.id === 'chronology-cause-effect' || flavour.id === 'evidence-to-conclusion' || flavour.id === 'case-to-concept')) score += 2;
  if ((subjectLower.includes('science') || subjectLower.includes('evs') || subjectLower.includes('geography')) && (flavour.id === 'classification' || flavour.id === 'process-first' || flavour.id === 'evidence-to-conclusion')) score += 2;
  if ((subjectLower.includes('hindi') || subjectLower.includes('english') || subjectLower.includes('language')) && (flavour.id === 'classification' || flavour.id === 'compare-and-contrast' || flavour.id === 'rule-exception')) score += 1;
  // Neutral tie-break anchor: when a topic/subject gives no real signal at
  // all (every flavour scores 0), the hash-based tie-break below would
  // otherwise land on an arbitrary-looking flavour (e.g. chronology-cause-
  // effect for a grammar topic) — this tiny nudge makes the safest generic
  // choice win those true no-signal ties without ever outweighing a real
  // keyword/subject match (3 and 2 points respectively).
  if (flavour.id === 'concept-first') score += 0.1;
  const idx = recentIds.indexOf(flavour.id);
  if (idx !== -1) score -= (recentIds.length - idx) * 1.5; // most-recent use penalized hardest
  return score;
}

/**
 * Picks a flavour for one topic. Never a blind cycle and never pure
 * randomness: every flavour is scored on topic-keyword and subject fit,
 * then a repetition penalty is subtracted for flavours used recently on the
 * same exam+subject (heavier penalty the more recent the use) — but the
 * penalty only demotes, so the strongest teaching fit still wins if nothing
 * comparable exists (repeating a flavour is fine when it's genuinely the
 * best fit; novelty for its own sake is never the goal). Ties among
 * near-equal top scores are broken with a hash of the topic/exam/subject
 * (not time or Math.random()), so the same inputs always resolve the same
 * way and a rerun is reproducible.
 *
 * @param {{topic:string, subject?:string, exam?:string}} ctx
 * @param {Array<{flavour?:string, exam?:string, subject?:string}>} recentMemory
 *   content-memory records, most-recent-first. Filtered internally to
 *   records matching ctx's exam and/or subject (loose: a record missing
 *   either field is treated as a match on that field so older records
 *   without a subject still count).
 */
function selectFlavour(ctx, recentMemory = []) {
  const topic = String(ctx.topic || '');
  const subject = String(ctx.subject || '');
  const exam = String(ctx.exam || '');
  const topicLower = topic.toLowerCase();
  const subjectLower = subject.toLowerCase();

  const recentIds = recentMemory
    .filter(r => r && r.flavour && (!exam || !r.exam || r.exam === exam) && (!subject || !r.subject || r.subject === subject))
    .slice(0, RECENT_WINDOW)
    .map(r => r.flavour);

  const scored = FLAVOUR_ENGINE.map(f => ({ flavour: f, score: scoreFlavour(f, topicLower, subjectLower, recentIds) }));
  scored.sort((a, b) => b.score - a.score);

  const top = scored[0].score;
  const tied = scored.filter(s => s.score >= top - TIE_EPSILON);
  const pick = tied[hashString(topic + '|' + exam + '|' + subject) % tied.length].flavour;

  return {
    selected: pick,
    candidates: scored.slice(0, 3).map(s => ({ id: s.flavour.id, score: s.score })),
    recentlyUsed: recentIds,
  };
}

/**
 * Renders the compact, model-facing block the Master Prompt's
 * {{FLAVOUR_ENGINE_BLOCK}} placeholder gets replaced with: the full menu
 * (so the model can override the suggestion when the topic genuinely calls
 * for something else — this is a recommendation, never a forced pick) plus
 * the engine's own suggestion and why. Never reveals internal scores/the
 * editorial plan itself — the model records its own actual choice in
 * Publisher Notes / the Content Memory block's "flavour" field.
 */
function buildFlavourPromptBlock(ctx, recentMemory = []) {
  const result = selectFlavour(ctx, recentMemory);
  const menu = FLAVOUR_ENGINE.map(f =>
    `- **${f.id}** — goal: ${f.goal}; flow: ${f.flow}; best for: ${f.best_for.join('; ')}`
  ).join('\n');
  const recentNote = result.recentlyUsed.length
    ? ` (recently used on this exam/subject: ${result.recentlyUsed.join(', ')} — a different flavour is preferred where teaching value is comparable)`
    : '';
  return `${menu}\n\nEngine suggestion for this topic: **${result.selected.id}**${recentNote}. This is a starting point, not a mandate — a flavour changes real teaching strategy (opening logic, sequence, example strategy, misconception treatment), not wording or card labels. Follow the suggestion unless the topic genuinely teaches better a different way; never pick a flavour merely to avoid repeating the last one. State your final flavour choice and why in Publisher Notes, and set it as the "flavour" field in the Content Memory block.`;
}

global.FlavourEngine = { FLAVOUR_ENGINE, selectFlavour, buildFlavourPromptBlock };
})(typeof window !== 'undefined' ? window : this);
