// AUTO-GENERATED by gen-validators-notes.mjs from notes-factory/index.html.
// Do not hand-edit — re-run the generator instead so this never drifts from
// the manual browser tool's actual "Run validation" gate.
import { JSDOM } from 'jsdom';
const DOMParser = new JSDOM('').window.DOMParser;
const TARGET_SITE_HOST = 'examnotespdf.in';
let state = { hindiPercent: 70 };
export function setHindiPercent(p){ state.hindiPercent = p; }

const REFERENCE_SOURCES_GENERAL = [
  { label: 'NCF 2005 (National Curriculum Framework)', url: 'https://ncert.nic.in/pdf/nc-framework/nf2005-english.pdf' },
  { label: 'NCF 2023 (School Education)', url: 'https://ncert.nic.in/pdf/NCF-2023-Enlish.pdf' },
  { label: 'NEP 2020', url: 'https://www.education.gov.in/sites/upload_files/mhrd/files/NEP_Final_English_0.pdf' },
  { label: 'RTE Act 2009', url: 'https://www.indiacode.nic.in/handle/123456789/1359' },
];

function vParseBody(html){ return new DOMParser().parseFromString(html || '', 'text/html'); }

function vProseText(doc){
  const clone = doc.body.cloneNode(true);
  clone.querySelectorAll('script,style,svg').forEach(n=>n.remove());
  return (clone.textContent || '').replace(/https?:\/\/\S+/g,' ').replace(/\s+/g,' ').trim();
}

function vWordCount(text){ return text ? text.split(/\s+/).filter(Boolean).length : 0; }

function vNormalize(s){ return String(s||'').toLowerCase().trim().replace(/\s+/g,' '); }

function vCountKeyphrase(text, keyphrase){
  const t = ' ' + vNormalize(text) + ' ';
  const k = vNormalize(keyphrase);
  if(!k) return { exact:0, variant:0, total:0 };
  const esc = k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const exact = (t.match(new RegExp('\\b'+esc+'\\b','g')) || []).length;
  const variantPattern = esc.replace(/[\s-]+/g,'[\\s-]+');
  const total = (t.match(new RegExp('\\b'+variantPattern+'\\b','g')) || []).length;
  return { exact, variant: Math.max(0,total-exact), total };
}

function vCheckImageAlt(doc, keyphrase){
  const imgs = [...doc.querySelectorAll('img')];
  const k = vNormalize(keyphrase);
  const alts = imgs.map(i=>i.getAttribute('alt')||'');
  const pass = imgs.length>=1 && alts.some(a=>vNormalize(a).startsWith(k)) && k.length>0;
  return { id:'image-alt', label:'≥1 <img> with ALT starting with keyphrase', tier:'hard', pass,
    detail: imgs.length===0 ? 'NO <img> TAGS FOUND IN BODY' : `${imgs.length} image(s), alt="${alts.join('" / "')}"` };
}

function vCheckParagraphs(doc){
  let longest=0, sample='';
  doc.querySelectorAll('p').forEach(p=>{ const w=vWordCount(p.textContent); if(w>longest){longest=w; sample=p.textContent.trim().slice(0,60);} });
  return { id:'paragraphs', label:'No <p> over 120 words', tier:'hard', pass: longest<=120,
    detail: `longest = ${longest} words${sample?` ("${sample}…")`:''}` };
}

function vCheckLinks(doc){
  let internal=0, external=0, externalNofollow=0, hashLinks=0;
  doc.querySelectorAll('a[href]').forEach(a=>{
    const href = (a.getAttribute('href')||'').trim();
    if(href==='#'){ hashLinks++; return; }
    if(/^https?:\/\//i.test(href)){
      let host=''; try{ host = new URL(href).hostname.replace(/^www\./,''); }catch(e){}
      if(host===TARGET_SITE_HOST) internal++;
      else { external++; if(/nofollow/i.test(a.getAttribute('rel')||'')) externalNofollow++; }
    } else if(href.startsWith('/')) internal++;
  });
  return { id:'links', label:'≥5 internal + ≥2 external links, zero href="#"', tier:'hard',
    pass: internal>=5 && external>=2 && hashLinks===0,
    detail: `${internal} internal, ${external} external (${externalNofollow} nofollow), ${hashLinks} href="#"` };
}

function vCheckDuplicateIds(doc){
  const ids = [...doc.querySelectorAll('[id]')].map(el=>el.id);
  const seen=new Set(), dupes=new Set();
  ids.forEach(id=>{ if(seen.has(id)) dupes.add(id); seen.add(id); });
  return { id:'dup-ids', label:'No duplicate id attributes', tier:'hard', pass: dupes.size===0,
    detail: dupes.size ? 'duplicated: '+[...dupes].join(', ') : `${ids.length} unique id(s)` };
}

function vCheckBareH3(doc){
  const h3s = [...doc.querySelectorAll('h3')];
  const bare = h3s.filter(h=>!(h.getAttribute('style')||'').trim());
  return { id:'bare-h3', label:'Every <h3> has an inline style (no bare h3)', tier:'hard', pass: bare.length===0,
    detail: `${h3s.length} total, ${bare.length} bare` };
}

function vCheckScriptTags(doc){
  const n = doc.querySelectorAll('script').length;
  return { id:'no-script', label:'Zero <script> tags in body', tier:'hard', pass: n===0, detail: `${n} found` };
}

function vCheckCitations(doc){
  const sups = [...doc.querySelectorAll('sup[id^="cite-"]')];
  const refs = [...doc.querySelectorAll('li[id^="ref-"]')];
  const supTargets = new Set(sups.map(s=>{ const a=s.querySelector('a[href^="#ref-"]'); return a ? a.getAttribute('href').slice(1) : null; }).filter(Boolean));
  const refIds = new Set(refs.map(r=>r.id));
  const orphanCitations = [...supTargets].filter(t=>!refIds.has(t));
  const orphanRefs = [...refIds].filter(id=>!supTargets.has(id));
  return { id:'citations', label:'≥4 inline citations, zero orphans either direction', tier:'hard',
    pass: sups.length>=4 && orphanCitations.length===0 && orphanRefs.length===0,
    detail: `${sups.length} citation(s), ${refs.length} reference(s), ${orphanCitations.length} orphan citation(s), ${orphanRefs.length} orphan reference(s)` };
}

function vCheckToc(doc){
  const h2Ids = new Set([...doc.querySelectorAll('h2[id]')].map(h=>h.id));
  const matching = [...doc.querySelectorAll('a[href^="#"]')].filter(a=>h2Ids.has(a.getAttribute('href').slice(1)));
  return { id:'toc', label:'Linked TOC present (proxy — Rank Math’s real TOC-plugin detection is unconfirmed, see audit)', tier:'soft',
    pass: matching.length>=2, detail: `${matching.length} anchor link(s) resolve to a real H2 id` };
}

function vCheckAdSlots(doc){
  const ads = [...doc.querySelectorAll('ins.adsbygoogle')];
  if(ads.length!==3) return { id:'ad-slots', label:'Exactly 3 ad slots, spread early/mid/late', tier:'soft', pass:false, detail:`${ads.length} found (need exactly 3)` };
  const allNodes = [...doc.body.querySelectorAll('*')];
  const total = allNodes.length || 1;
  const thirds = ads.map(ad=>{
    const idx = allNodes.indexOf(ad.parentElement || ad);
    const frac = idx/total;
    return frac<1/3 ? 'early' : frac<2/3 ? 'middle' : 'late';
  });
  const pass = new Set(thirds).size>=2 && !(thirds[0]==='late' && thirds[1]==='late' && thirds[2]==='late');
  return { id:'ad-slots', label:'3 ad slots spread across zones, not bunched at the end', tier:'soft', pass, detail: `positions: ${thirds.join(', ')}` };
}

function vCheckTitle(seo){
  const k = vNormalize(seo.focusKeyword), t = seo.seoTitle||'';
  return { id:'title', label:'SEO Title starts with keyphrase, ≤60 chars', tier:'hard',
    pass: k.length>0 && vNormalize(t).startsWith(k) && t.length<=60, detail: `"${t}" (${t.length} chars)` };
}

function vCheckMeta(seo){
  const m = seo.metaDescription||'';
  const count = vCountKeyphrase(m, seo.focusKeyword).total;
  return { id:'meta', label:'Meta description 150–155 chars, keyphrase exactly once', tier:'hard',
    pass: m.length>=150 && m.length<=155 && count===1, detail: `${m.length} chars, keyphrase found ${count}x` };
}

function vCheckSlug(seo){
  const slug = seo.slug||'';
  const kwWords = vNormalize(seo.focusKeyword).split(' ').filter(Boolean);
  const slugWords = slug.split('-');
  const pass = slug.length>0 && slug.length<75 && /^[a-z0-9-]+$/.test(slug) && kwWords.every(w=>slugWords.includes(w));
  return { id:'slug', label:'Slug has every keyphrase word, <75 chars', tier:'hard', pass, detail: `"${slug}" (${slug.length} chars)` };
}

function vCheckH1(seo){
  const k = vNormalize(seo.focusKeyword), h1 = seo.h1||'';
  const hindiPercent = (typeof state !== 'undefined' && typeof state.hindiPercent === 'number') ? state.hindiPercent : 70;
  if (hindiPercent >= 50) {
    const hasDevanagari = /[ऀ-ॿ]/.test(h1);
    return { id:'h1', label:'H1 is a real Hindi-language heading (language-mix aware)', tier:'hard', pass: h1.trim().length>=10 && hasDevanagari, detail: `"${h1}"` };
  }
  return { id:'h1', label:'H1 starts with keyphrase', tier:'hard', pass: k.length>0 && vNormalize(h1).startsWith(k), detail: `"${h1}"` };
}

function vCheckFirst100Words(doc, seo){
  const words = vProseText(doc).split(/\s+/).filter(Boolean).slice(0,100).join(' ');
  const pass = vCountKeyphrase(words, seo.focusKeyword).total>=1;
  return { id:'first-100', label:'Keyphrase in first 100 words of BODY text (not just the WP title)', tier:'hard',
    pass, detail: pass ? 'found' : 'not found in: "'+words.slice(0,120)+'…"' };
}

function vCheckPipelineArtifacts(bodyHtml, seo){
  seo = seo || {};
  const html = String(bodyHtml||'');
  const hay = html + ' ' + JSON.stringify(seo);
  const offenders = [];

  const bracketPatterns = [
    /\[exact keyphrase\]/i, /\[insert[^\]]*\]/i, /\[write here\]/i,
    /\[entire notes body html\]/i, /\[per formula above[^\]]*\]/i,
    /\[\s*n\s*\]/i, /\[\s*list[^\]]*\]/i
  ];
  for(const re of bracketPatterns){ if(re.test(hay)){ offenders.push(`unresolved template placeholder matching ${re}`); break; } }
  const proseOnly = html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
  if(proseOnly && /^\[[^\]]{1,120}\]$/.test(proseOnly)){ offenders.push('body is nothing but a single bracketed placeholder'); }

  // via.placeholder.com is EXPECTED exactly once, in the mandatory featured
  // <img> the VISUAL/HTML SYSTEM requires right after the intro — a human
  // replaces it with the real uploaded image before hitting Publish on a
  // draft (publish-note.yml, unlike publish-long-post.yml, has no automatic
  // media-upload/swap step). Only flag it showing up more than once, or
  // outside an <img> tag (e.g. the AI mentioning it in prose by mistake).
  const placeholderImgs = (html.match(/<img[^>]*via\.placeholder\.com[^>]*>/gi)||[]).length;
  const otherPlaceholderMentions = (html.match(/via\.placeholder\.com/gi)||[]).length - placeholderImgs;
  if(placeholderImgs > 1) offenders.push('more than one placeholder <img> tag found (expected exactly 1)');
  if(otherPlaceholderMentions > 0) offenders.push('via.placeholder.com text found outside the mandatory <img> tag');
  if(/lorem ipsum/i.test(html)) offenders.push('Lorem ipsum filler text');
  if(proseOnly === 'undefined' || proseOnly === 'null') offenders.push(`body is literally "${proseOnly}"`);
  if(/^\s*(?:html|htm)\s*\n/i.test(html)) offenders.push('leaked markdown fence language word ("html") before the first tag');
  // A chart block's JSON spec must be consumed by the chart renderer, never shipped
  // as visible text. Seeing it in the body means the AI wrote a {* chart *} block this
  // page's renderer didn't know — i.e. the fetched prompt and this loaded tool are
  // different versions. Hard-fail rather than publish a wall of raw JSON to readers.
  if(/"kind"\s*:\s*"(grid|flow|timeline|bars|comparison|tree)"/i.test(proseOnly)) offenders.push('raw chart JSON leaked into the body — the prompt and this tool are out of sync (this page does not know the {* chart *} block type; reload it)');
  // The "block title still starts with a type keyword" check (e.g. a card
  // literally titled "chart: ...") was removed here -- it only made sense
  // for the OLD {* type: title *} block-tag system, where a failed parse
  // left the raw marker text visible. v13 hand-writes real HTML directly
  // (HARD BAN 8: "there is no publisher script rendering card markup for
  // Notes"), so that failure mode can't happen any more, and the check was
  // firing on ordinary English card labels that legitimately start with a
  // word like "Question" or "Table" (e.g. "Question 1 (Direct)"), a much
  // more common false positive than the "Table of Contents" one already
  // patched here before this was fully removed.


  return { id:'pipeline-artifacts', label:'No leaked AI-scaffolding / placeholder artifacts', tier:'hard',
    pass: offenders.length===0, detail: offenders.length ? offenders.join('; ') : 'clean' };
}

function vRunChecks(seo, bodyHtml){
  seo = seo || {};
  const doc = vParseBody(bodyHtml);
  const checks = [
    vCheckPipelineArtifacts(bodyHtml, seo),
    vCheckImageAlt(doc, seo.focusKeyword),
    vCheckParagraphs(doc), vCheckLinks(doc), vCheckDuplicateIds(doc), vCheckBareH3(doc),
    vCheckScriptTags(doc), vCheckCitations(doc), vCheckToc(doc), vCheckAdSlots(doc),
    vCheckTitle(seo), vCheckMeta(seo), vCheckSlug(seo), vCheckH1(seo),
    vCheckFirst100Words(doc, seo)
  ];
  const hardChecks = checks.filter(c=>c.tier==='hard');
  return { checks, hardFails: hardChecks.filter(c=>!c.pass), hardPass: hardChecks.every(c=>c.pass),
    softWarnings: checks.filter(c=>c.tier==='soft' && !c.pass) };
}

export { vRunChecks, vParseBody, vCheckPipelineArtifacts };
